etcd:
  version: ${etcd_version}
  discovery: ${discovery_url}
  name: "{HOSTNAME}"

  advertise_client_urls: https://{PRIVATE_IPV4}:${etcd_client_port}
  initial_advertise_peer_urls: https://{PRIVATE_IPV4}:${etcd_peer_port}
  listen_client_urls: https://0.0.0.0:${etcd_client_port}
  listen_peer_urls: https://{PRIVATE_IPV4}:${etcd_peer_port}

  peer_client_cert_auth: true
  peer_trusted_ca_file: ${ca_cert_file}
  peer_cert_file: ${cert_file}
  peer_key_file: ${key_file}

  client_cert_auth: true
  trusted_ca_file: ${ca_cert_file}
  cert_file: ${cert_file}
  key_file: ${key_file}

storage:
  files:
    - path: ${ca_cert_file}
      filesystem: root
      mode: 0644
      contents:
        inline: ${ca_cert}
      user:
        id: 500
      group:
        id: 500
