kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: gcr.io/google_containers/guestbook:v3
        ports:
        - name: http-server
          containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
    nodePort: 32100
  selector:
    app: guestbook
  type: NodePort
