kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: heapster
  labels:
    app: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        ports:
        - name: http-server
          containerPort: 8082
        command:
        - /heapster
        - --source=kubernetes:${apiserver_endpoint}
        - --sink=influxdb:http://influxdb:8086
        volumeMounts:
        - name: tls
          mountPath: /opt/k8s/tls
          readOnly: true
      volumes:
      - name: tls
        hostPath:
          path: /opt/k8s/tls
---
kind: Service
apiVersion: v1
metadata:
  name: heapster
  labels:
    app: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: heapster
