kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.6
        ports:
        - name: influxdb-api
          containerPort: 8086
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: influxdb
  labels:
    app: influxdb
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 8086
    targetPort: influxdb-api
  selector:
    app: influxdb
